### ISSUE TITLE
Line number

### ISSUE THREAD

**Issue by mj-ee** [alvinwan/TexSoup#66] opened 2019-04-19 18:35 UTC
Is there a possibility to get the exact line number of where a LaTeX command was declared or written in the original LaTeX file? @alvinwan 

**EDIT:** TokenWithPosition, gives you only index position of the string.

**Comment by alvinwan** [comment] 2019-04-20 21:04
I believe this is what #60 is suggesting too. Just following up from our email thread, here's what I suggested:

> I would do the following; in general, I would have all nodes in the parse tree store absolute position in the original doc, then use the CharToLineOffset util to convert absolute positions to (lineno, charoffset):
> 
> 1. Make all nodes position-aware (pass/set a position attribute in the constructor): https://github.com/alvinwan/TexSoup/blob/master/TexSoup/data.py#L549
> 2. Equip all tokens with positions: https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L120 (by wrapping all text with `TokenWithPosition`. You can access absolute position using `text.position`, like here: https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L206)
> 3. Modify reader to “unpack” token with positions for commands (meaning use `TokenWithPosition`’s string for the command name and use the `TokenWithPosition`’s position for the node position that you defined in step 1): https://github.com/alvinwan/TexSoup/blob/master/TexSoup/reader.py#L255
> 4. Amend https://github.com/alvinwan/TexSoup/blob/master/TexSoup/data.py#L18 to offer lineno and lineoffset `@property`s (or whatever you want to name them), using CharLinetoOffset and the node’s absolute position.
> 
> I also think it’s weird that the TexNode takes in the `src` in the constructor. If anything, `CharLinetoOffset` should be initialized outside of `TexNode`. Then, the initialized object instead of the raw `src` is passed to `TexNode` here: https://github.com/alvinwan/TexSoup/blob/master/TexSoup/__init__.py#L84

**Comment by alvinwan** [comment] 2020-07-20 11:53
(Closing, as this is a duplicate of #60 -- will continue discussion in #60)

**Closed by alvinwan** 2020-07-20 11:53 UTC
